namespace Save_HMI_Controls
{
    partial class Cascader
    {
        /// <summary> 
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region 组件设计器生成的代码

        /// <summary> 
        /// 设计器支持所需的方法 - 不要修改
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            LYHControls.CascaderOption cascaderOption212 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption213 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption214 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption215 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption216 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption217 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption218 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption219 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption220 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption221 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption222 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption223 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption224 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption225 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption226 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption227 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption228 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption229 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption230 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption231 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption232 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption233 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption234 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption235 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption236 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption237 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption238 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption239 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption240 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption241 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption242 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption243 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption244 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption245 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption246 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption247 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption248 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption249 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption250 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption251 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption252 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption253 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption254 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption255 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption256 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption257 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption258 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption259 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption260 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption261 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption262 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption263 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption264 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption265 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption266 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption267 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption268 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption269 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption270 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption271 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption272 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption273 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption274 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption275 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption276 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption277 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption278 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption279 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption280 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption281 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption282 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption283 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption284 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption285 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption286 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption287 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption288 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption289 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption290 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption291 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption292 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption293 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption294 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption295 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption296 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption297 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption298 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption299 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption300 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption301 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption302 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption303 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption304 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption305 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption306 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption307 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption308 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption309 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption310 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption311 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption312 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption313 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption314 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption315 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption316 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption317 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption318 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption319 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption320 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption321 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption322 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption323 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption324 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption325 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption326 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption327 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption328 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption329 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption330 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption331 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption332 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption333 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption334 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption335 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption336 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption337 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption338 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption339 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption340 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption341 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption342 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption343 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption344 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption345 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption346 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption347 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption348 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption349 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption350 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption351 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption352 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption353 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption354 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption355 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption356 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption357 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption358 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption359 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption360 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption361 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption362 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption363 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption364 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption365 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption366 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption367 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption368 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption369 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption370 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption371 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption372 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption373 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption374 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption375 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption376 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption377 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption378 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption379 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption380 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption381 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption382 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption383 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption384 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption385 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption386 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption387 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption388 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption389 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption390 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption391 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption392 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption393 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption394 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption395 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption396 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption397 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption398 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption399 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption400 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption401 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption402 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption403 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption404 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption405 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption406 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption407 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption408 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption409 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption410 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption411 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption412 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption413 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption414 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption415 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption416 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption417 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption418 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption419 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption420 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption421 = new LYHControls.CascaderOption();
            LYHControls.CascaderOption cascaderOption422 = new LYHControls.CascaderOption();
            smoothScrollPanel1 = new SmoothScrollPanel();
            smoothScrollPanel2 = new SmoothScrollPanel();
            cascader14 = new LYHControls.Cascader();
            label21 = new Label();
            smoothScrollPanel3 = new LYHControls.SmoothScrollPanel();
            inputText1 = new LYHControls.InputText();
            cascader13 = new LYHControls.Cascader();
            multi_funcButton1 = new LYHControls.Multi_funcButton(components);
            label23 = new Label();
            label27 = new Label();
            label29 = new Label();
            cascader10 = new LYHControls.Cascader();
            label17 = new Label();
            cascader11 = new LYHControls.Cascader();
            label18 = new Label();
            cascader12 = new LYHControls.Cascader();
            label19 = new Label();
            label20 = new Label();
            cascader9 = new LYHControls.Cascader();
            label16 = new Label();
            cascader7 = new LYHControls.Cascader();
            label10 = new Label();
            cascader8 = new LYHControls.Cascader();
            label12 = new Label();
            label15 = new Label();
            cascader6 = new LYHControls.Cascader();
            label9 = new Label();
            cascader5 = new LYHControls.Cascader();
            cascader4 = new LYHControls.Cascader();
            cascader3 = new LYHControls.Cascader();
            cascader2 = new LYHControls.Cascader();
            label7 = new Label();
            label8 = new Label();
            cascader1 = new LYHControls.Cascader();
            label6 = new Label();
            label4 = new Label();
            label3 = new Label();
            label5 = new Label();
            label13 = new Label();
            label1 = new Label();
            panel1 = new Panel();
            label14 = new Label();
            label11 = new Label();
            label2 = new Label();
            smoothScrollPanel1.SuspendLayout();
            smoothScrollPanel2.SuspendLayout();
            smoothScrollPanel3.SuspendLayout();
            panel1.SuspendLayout();
            SuspendLayout();
            // 
            // smoothScrollPanel1
            // 
            smoothScrollPanel1.AutoScroll = true;
            smoothScrollPanel1.AutoScrollMinSize = new Size(0, 1137);
            smoothScrollPanel1.BackColor = Color.White;
            smoothScrollPanel1.BorderColor = Color.FromArgb(200, 200, 200);
            smoothScrollPanel1.BorderRadius = 0;
            smoothScrollPanel1.BorderWidth = 1;
            smoothScrollPanel1.BottomPadding = 50;
            smoothScrollPanel1.Controls.Add(smoothScrollPanel2);
            smoothScrollPanel1.EndBackColor = Color.FromArgb(240, 240, 240);
            smoothScrollPanel1.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            smoothScrollPanel1.Location = new Point(0, 0);
            smoothScrollPanel1.Name = "smoothScrollPanel1";
            smoothScrollPanel1.Padding = new Padding(1);
            smoothScrollPanel1.ScrollBarColor = Color.FromArgb(120, 0, 0, 0);
            smoothScrollPanel1.ScrollBarWidth = 6;
            smoothScrollPanel1.ShowCustomScrollbar = true;
            smoothScrollPanel1.Size = new Size(1700, 990);
            smoothScrollPanel1.StartBackColor = Color.White;
            smoothScrollPanel1.TabIndex = 10;
            smoothScrollPanel1.UseGradient = false;
            // 
            // smoothScrollPanel2
            // 
            smoothScrollPanel2.AutoScroll = true;
            smoothScrollPanel2.AutoScrollMinSize = new Size(0, 1033);
            smoothScrollPanel2.BackColor = Color.White;
            smoothScrollPanel2.BorderColor = Color.FromArgb(200, 200, 200);
            smoothScrollPanel2.BorderRadius = 0;
            smoothScrollPanel2.BorderWidth = 2;
            smoothScrollPanel2.BottomPadding = 0;
            smoothScrollPanel2.Controls.Add(cascader14);
            smoothScrollPanel2.Controls.Add(label21);
            smoothScrollPanel2.Controls.Add(smoothScrollPanel3);
            smoothScrollPanel2.Controls.Add(label29);
            smoothScrollPanel2.Controls.Add(cascader10);
            smoothScrollPanel2.Controls.Add(label17);
            smoothScrollPanel2.Controls.Add(cascader11);
            smoothScrollPanel2.Controls.Add(label18);
            smoothScrollPanel2.Controls.Add(cascader12);
            smoothScrollPanel2.Controls.Add(label19);
            smoothScrollPanel2.Controls.Add(label20);
            smoothScrollPanel2.Controls.Add(cascader9);
            smoothScrollPanel2.Controls.Add(label16);
            smoothScrollPanel2.Controls.Add(cascader7);
            smoothScrollPanel2.Controls.Add(label10);
            smoothScrollPanel2.Controls.Add(cascader8);
            smoothScrollPanel2.Controls.Add(label12);
            smoothScrollPanel2.Controls.Add(label15);
            smoothScrollPanel2.Controls.Add(cascader6);
            smoothScrollPanel2.Controls.Add(label9);
            smoothScrollPanel2.Controls.Add(cascader5);
            smoothScrollPanel2.Controls.Add(cascader4);
            smoothScrollPanel2.Controls.Add(cascader3);
            smoothScrollPanel2.Controls.Add(cascader2);
            smoothScrollPanel2.Controls.Add(label7);
            smoothScrollPanel2.Controls.Add(label8);
            smoothScrollPanel2.Controls.Add(cascader1);
            smoothScrollPanel2.Controls.Add(label6);
            smoothScrollPanel2.Controls.Add(label4);
            smoothScrollPanel2.Controls.Add(label3);
            smoothScrollPanel2.Controls.Add(label5);
            smoothScrollPanel2.Controls.Add(label13);
            smoothScrollPanel2.Controls.Add(label1);
            smoothScrollPanel2.Controls.Add(panel1);
            smoothScrollPanel2.EndBackColor = Color.FromArgb(240, 240, 240);
            smoothScrollPanel2.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            smoothScrollPanel2.Location = new Point(34, 24);
            smoothScrollPanel2.Name = "smoothScrollPanel2";
            smoothScrollPanel2.Padding = new Padding(1);
            smoothScrollPanel2.ScrollBarColor = Color.FromArgb(120, 0, 0, 0);
            smoothScrollPanel2.ScrollBarWidth = 6;
            smoothScrollPanel2.ShowCustomScrollbar = true;
            smoothScrollPanel2.Size = new Size(1631, 1063);
            smoothScrollPanel2.StartBackColor = Color.White;
            smoothScrollPanel2.TabIndex = 1;
            smoothScrollPanel2.UseGradient = false;
            // 
            // cascader14
            // 
            cascader14.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader14.ArrowSize = 8;
            cascader14.BackColor = Color.White;
            cascader14.CornerRadius = 6;
            cascader14.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader14.FillColor = Color.FromArgb(245, 245, 245);
            cascader14.FocusBorderColor = Color.FromArgb(250, 173, 20);
            cascader14.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader14.Location = new Point(1272, 630);
            cascader14.Name = "cascader14";
            cascaderOption214.Label = "React组";
            cascaderOption214.Value = "";
            cascaderOption215.Label = "Vue组";
            cascaderOption215.Value = "";
            cascaderOption213.Children.Add(cascaderOption214);
            cascaderOption213.Children.Add(cascaderOption215);
            cascaderOption213.Label = "前端组";
            cascaderOption213.Value = "";
            cascaderOption217.Label = "";
            cascaderOption217.Value = "";
            cascaderOption218.Label = "";
            cascaderOption218.Value = "";
            cascaderOption216.Children.Add(cascaderOption217);
            cascaderOption216.Children.Add(cascaderOption218);
            cascaderOption216.Disabled = true;
            cascaderOption216.Label = "后端组";
            cascaderOption216.Value = "";
            cascaderOption212.Children.Add(cascaderOption213);
            cascaderOption212.Children.Add(cascaderOption216);
            cascaderOption212.Label = "技术部";
            cascaderOption212.Value = "";
            cascaderOption220.Label = "产品经理";
            cascaderOption220.Value = "";
            cascaderOption221.Label = "设计师";
            cascaderOption221.Value = "";
            cascaderOption219.Children.Add(cascaderOption220);
            cascaderOption219.Children.Add(cascaderOption221);
            cascaderOption219.Label = "产品部";
            cascaderOption219.Value = "";
            cascader14.Options.Add(cascaderOption212);
            cascader14.Options.Add(cascaderOption219);
            cascader14.Placeholder = "选择部门";
            cascader14.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader14.SelectedForeColor = Color.FromArgb(250, 173, 20);
            cascader14.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader14.Size = new Size(196, 32);
            cascader14.TabIndex = 132;
            cascader14.Text = " ";
            // 
            // label21
            // 
            label21.AutoSize = true;
            label21.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label21.ForeColor = Color.FromArgb(98, 116, 142);
            label21.Location = new Point(1268, 590);
            label21.Name = "label21";
            label21.Size = new Size(37, 19);
            label21.TabIndex = 131;
            label21.Text = "黄色";
            // 
            // smoothScrollPanel3
            // 
            smoothScrollPanel3.AutoScroll = true;
            smoothScrollPanel3.AutoScrollMinSize = new Size(0, 268);
            smoothScrollPanel3.BackColor = Color.FromArgb(239, 246, 255);
            smoothScrollPanel3.BorderColor = Color.FromArgb(200, 200, 200);
            smoothScrollPanel3.BorderRadius = 0;
            smoothScrollPanel3.BorderWidth = 0;
            smoothScrollPanel3.BottomPadding = 0;
            smoothScrollPanel3.Controls.Add(inputText1);
            smoothScrollPanel3.Controls.Add(cascader13);
            smoothScrollPanel3.Controls.Add(multi_funcButton1);
            smoothScrollPanel3.Controls.Add(label23);
            smoothScrollPanel3.Controls.Add(label27);
            smoothScrollPanel3.EndBackColor = Color.FromArgb(240, 240, 240);
            smoothScrollPanel3.GradientMode = System.Drawing.Drawing2D.LinearGradientMode.Vertical;
            smoothScrollPanel3.Location = new Point(38, 749);
            smoothScrollPanel3.Name = "smoothScrollPanel3";
            smoothScrollPanel3.Padding = new Padding(1);
            smoothScrollPanel3.ScrollBarColor = Color.FromArgb(120, 0, 0, 0);
            smoothScrollPanel3.ScrollBarWidth = 6;
            smoothScrollPanel3.ShowCustomScrollbar = true;
            smoothScrollPanel3.Size = new Size(659, 284);
            smoothScrollPanel3.StartBackColor = Color.White;
            smoothScrollPanel3.TabIndex = 130;
            smoothScrollPanel3.UseGradient = false;
            // 
            // inputText1
            // 
            inputText1.ActiveColor = Color.FromArgb(24, 144, 255);
            inputText1.AutoComplete = false;
            inputText1.BackColor = Color.White;
            inputText1.BorderRadius = 6;
            inputText1.BorderWidth = 1F;
            inputText1.ClearIcon = null;
            inputText1.ClearIconColor = Color.FromArgb(140, 140, 140);
            inputText1.ClearIconHoverColor = Color.FromArgb(64, 169, 255);
            inputText1.ClearIconSize = 14;
            inputText1.DefaultBorderColor = Color.FromArgb(217, 217, 217);
            inputText1.DropDownBackColor = Color.FromArgb(242, 242, 242);
            inputText1.DropDownHoverItemColor = Color.FromArgb(35, 24, 144, 255);
            inputText1.DropDownSelectedItemBackColor = Color.FromArgb(24, 144, 255);
            inputText1.DropDownSelectedItemTextColor = Color.White;
            inputText1.DropDownTextColor = Color.FromArgb(38, 38, 38);
            inputText1.FilledVariantBackColor = Color.FromArgb(245, 245, 245);
            inputText1.InputBackgroundImage = null;
            inputText1.Location = new Point(20, 167);
            inputText1.Name = "inputText1";
            inputText1.PlaceholderColor = Color.FromArgb(191, 191, 191);
            inputText1.PlaceholderText = "请输入详细地址";
            inputText1.PrefixIcon = null;
            inputText1.PrefixIconColor = Color.FromArgb(140, 140, 140);
            inputText1.PrefixIconSize = new Size(16, 16);
            inputText1.Size = new Size(576, 42);
            inputText1.TabIndex = 126;
            inputText1.Variant = LYHControls.InputVariant.Outlined;
            // 
            // cascader13
            // 
            cascader13.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader13.ArrowSize = 8;
            cascader13.BackColor = Color.FromArgb(243, 244, 246);
            cascader13.CornerRadius = 6;
            cascader13.FillColor = Color.FromArgb(245, 245, 245);
            cascader13.FocusBorderColor = Color.FromArgb(20, 184, 166);
            cascader13.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader13.Location = new Point(20, 71);
            cascader13.Name = "cascader13";
            cascaderOption224.Label = "游仙区";
            cascaderOption224.Value = "";
            cascaderOption223.Children.Add(cascaderOption224);
            cascaderOption223.Label = "锦阳市";
            cascaderOption223.Value = "";
            cascaderOption226.Label = "青羊区";
            cascaderOption226.Value = "";
            cascaderOption227.Label = "锦江区";
            cascaderOption227.Value = "";
            cascaderOption228.Label = "武侯区";
            cascaderOption228.Value = "";
            cascaderOption225.Children.Add(cascaderOption226);
            cascaderOption225.Children.Add(cascaderOption227);
            cascaderOption225.Children.Add(cascaderOption228);
            cascaderOption225.Label = "成都市";
            cascaderOption225.Value = "";
            cascaderOption222.Children.Add(cascaderOption223);
            cascaderOption222.Children.Add(cascaderOption225);
            cascaderOption222.Label = "四川省";
            cascaderOption222.Value = "";
            cascaderOption231.Label = "越秀区";
            cascaderOption231.Value = "";
            cascaderOption232.Label = "天河区";
            cascaderOption232.Value = "";
            cascaderOption230.Children.Add(cascaderOption231);
            cascaderOption230.Children.Add(cascaderOption232);
            cascaderOption230.Label = "广州市";
            cascaderOption230.Value = "";
            cascaderOption234.Label = "福田区";
            cascaderOption234.Value = "";
            cascaderOption235.Label = "南山区";
            cascaderOption235.Value = "";
            cascaderOption233.Children.Add(cascaderOption234);
            cascaderOption233.Children.Add(cascaderOption235);
            cascaderOption233.Label = "深圳市";
            cascaderOption233.Value = "";
            cascaderOption229.Children.Add(cascaderOption230);
            cascaderOption229.Children.Add(cascaderOption233);
            cascaderOption229.Label = "广东省";
            cascaderOption229.Value = "";
            cascaderOption237.Label = "朝阳区";
            cascaderOption237.Value = "";
            cascaderOption238.Label = "海淀区";
            cascaderOption238.Value = "";
            cascaderOption236.Children.Add(cascaderOption237);
            cascaderOption236.Children.Add(cascaderOption238);
            cascaderOption236.Label = "北京市";
            cascaderOption236.Value = "";
            cascader13.Options.Add(cascaderOption222);
            cascader13.Options.Add(cascaderOption229);
            cascader13.Options.Add(cascaderOption236);
            cascader13.Placeholder = "请选择省 / 市 / 区";
            cascader13.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader13.SelectedForeColor = Color.FromArgb(20, 184, 166);
            cascader13.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader13.Size = new Size(256, 42);
            cascader13.TabIndex = 125;
            cascader13.Text = "cascader13";
            // 
            // multi_funcButton1
            // 
            multi_funcButton1.ActiveBackColor = Color.Empty;
            multi_funcButton1.ActiveBackgroundImage = null;
            multi_funcButton1.ActiveTextColor = Color.Empty;
            multi_funcButton1.AutoCheckOnClick = true;
            multi_funcButton1.BackColor = Color.Transparent;
            multi_funcButton1.Checked = false;
            multi_funcButton1.CheckedText = null;
            multi_funcButton1.ClickMode = LYHControls.Multi_funcButton.ButtonClickMode.Momentary;
            multi_funcButton1.CornerRadius = 6;
            multi_funcButton1.FillType = LYHControls.Multi_funcButton.ButtonFillType.Solid;
            multi_funcButton1.Font = new Font("HarmonyOS Sans SC", 11.2499981F, FontStyle.Regular, GraphicsUnit.Point, 134);
            multi_funcButton1.IconPos = LYHControls.Multi_funcButton.IconPosition.Left;
            multi_funcButton1.IconSize = new Size(16, 16);
            multi_funcButton1.IconSpacing = 8;
            multi_funcButton1.IsWaiting = false;
            multi_funcButton1.Location = new Point(20, 231);
            multi_funcButton1.Name = "multi_funcButton1";
            multi_funcButton1.NormalBackgroundImage = null;
            multi_funcButton1.NormalIcon = null;
            multi_funcButton1.NormalTextColor = Color.Empty;
            multi_funcButton1.PressedIcon = null;
            multi_funcButton1.Size = new Size(619, 37);
            multi_funcButton1.TabIndex = 119;
            multi_funcButton1.Text = "保存地址";
            multi_funcButton1.ThemeColor = Color.FromArgb(20, 184, 166);
            // 
            // label23
            // 
            label23.AutoSize = true;
            label23.Font = new Font("HarmonyOS Sans SC", 16F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label23.ForeColor = Color.FromArgb(30, 41, 57);
            label23.Location = new Point(20, 130);
            label23.Name = "label23";
            label23.Size = new Size(85, 21);
            label23.TabIndex = 117;
            label23.Text = "详细地址 *";
            // 
            // label27
            // 
            label27.AutoSize = true;
            label27.Font = new Font("HarmonyOS Sans SC", 16F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label27.ForeColor = Color.FromArgb(30, 41, 57);
            label27.Location = new Point(20, 33);
            label27.Name = "label27";
            label27.Size = new Size(85, 21);
            label27.TabIndex = 112;
            label27.Text = "收货地区 *";
            // 
            // label29
            // 
            label29.AutoSize = true;
            label29.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label29.ForeColor = Color.FromArgb(30, 41, 57);
            label29.Location = new Point(35, 695);
            label29.Name = "label29";
            label29.Size = new Size(192, 26);
            label29.TabIndex = 129;
            label29.Text = "实际应用 - 预订表单";
            // 
            // cascader10
            // 
            cascader10.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader10.ArrowSize = 8;
            cascader10.BackColor = Color.White;
            cascader10.CornerRadius = 6;
            cascader10.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader10.FillColor = Color.FromArgb(245, 245, 245);
            cascader10.FocusBorderColor = Color.FromArgb(16, 185, 129);
            cascader10.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader10.Location = new Point(850, 630);
            cascader10.Name = "cascader10";
            cascaderOption241.Label = "React组";
            cascaderOption241.Value = "";
            cascaderOption242.Label = "Vue组";
            cascaderOption242.Value = "";
            cascaderOption240.Children.Add(cascaderOption241);
            cascaderOption240.Children.Add(cascaderOption242);
            cascaderOption240.Label = "前端组";
            cascaderOption240.Value = "";
            cascaderOption244.Label = "";
            cascaderOption244.Value = "";
            cascaderOption245.Label = "";
            cascaderOption245.Value = "";
            cascaderOption243.Children.Add(cascaderOption244);
            cascaderOption243.Children.Add(cascaderOption245);
            cascaderOption243.Disabled = true;
            cascaderOption243.Label = "后端组";
            cascaderOption243.Value = "";
            cascaderOption239.Children.Add(cascaderOption240);
            cascaderOption239.Children.Add(cascaderOption243);
            cascaderOption239.Label = "技术部";
            cascaderOption239.Value = "";
            cascaderOption247.Label = "产品经理";
            cascaderOption247.Value = "";
            cascaderOption248.Label = "设计师";
            cascaderOption248.Value = "";
            cascaderOption246.Children.Add(cascaderOption247);
            cascaderOption246.Children.Add(cascaderOption248);
            cascaderOption246.Label = "产品部";
            cascaderOption246.Value = "";
            cascader10.Options.Add(cascaderOption239);
            cascader10.Options.Add(cascaderOption246);
            cascader10.Placeholder = "选择部门";
            cascader10.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader10.SelectedForeColor = Color.FromArgb(16, 185, 129);
            cascader10.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader10.Size = new Size(196, 32);
            cascader10.TabIndex = 128;
            cascader10.Text = " ";
            // 
            // label17
            // 
            label17.AutoSize = true;
            label17.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label17.ForeColor = Color.FromArgb(98, 116, 142);
            label17.Location = new Point(846, 590);
            label17.Name = "label17";
            label17.Size = new Size(37, 19);
            label17.TabIndex = 127;
            label17.Text = "绿色";
            // 
            // cascader11
            // 
            cascader11.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader11.ArrowSize = 8;
            cascader11.BackColor = Color.White;
            cascader11.CornerRadius = 6;
            cascader11.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader11.FillColor = Color.FromArgb(245, 245, 245);
            cascader11.FocusBorderColor = Color.FromArgb(139, 92, 246);
            cascader11.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader11.Location = new Point(437, 630);
            cascader11.Name = "cascader11";
            cascaderOption251.Label = "Android";
            cascaderOption251.Value = "";
            cascaderOption252.Label = "IPhone";
            cascaderOption252.Value = "";
            cascaderOption250.Children.Add(cascaderOption251);
            cascaderOption250.Children.Add(cascaderOption252);
            cascaderOption250.Label = "手机";
            cascaderOption250.Value = "";
            cascaderOption254.Label = "笔记本";
            cascaderOption254.Value = "";
            cascaderOption255.Label = "台式机";
            cascaderOption255.Value = "";
            cascaderOption253.Children.Add(cascaderOption254);
            cascaderOption253.Children.Add(cascaderOption255);
            cascaderOption253.Label = "电脑";
            cascaderOption253.Value = "";
            cascaderOption249.Children.Add(cascaderOption250);
            cascaderOption249.Children.Add(cascaderOption253);
            cascaderOption249.Label = "电子产品";
            cascaderOption249.Value = "";
            cascaderOption258.Label = "半身裙";
            cascaderOption258.Value = "";
            cascaderOption259.Label = "连衣裙";
            cascaderOption259.Value = "";
            cascaderOption257.Children.Add(cascaderOption258);
            cascaderOption257.Children.Add(cascaderOption259);
            cascaderOption257.Label = "女装";
            cascaderOption257.Value = "";
            cascaderOption261.Label = "牛仔裤";
            cascaderOption261.Value = "";
            cascaderOption262.Label = "T恤";
            cascaderOption262.Value = "";
            cascaderOption260.Children.Add(cascaderOption261);
            cascaderOption260.Children.Add(cascaderOption262);
            cascaderOption260.Label = "男装";
            cascaderOption260.Value = "";
            cascaderOption256.Children.Add(cascaderOption257);
            cascaderOption256.Children.Add(cascaderOption260);
            cascaderOption256.Label = "服装";
            cascaderOption256.Value = "";
            cascader11.Options.Add(cascaderOption249);
            cascader11.Options.Add(cascaderOption256);
            cascader11.Placeholder = "选择分类";
            cascader11.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader11.SelectedForeColor = Color.FromArgb(139, 92, 246);
            cascader11.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader11.Size = new Size(196, 32);
            cascader11.TabIndex = 126;
            cascader11.Text = "cascader11";
            // 
            // label18
            // 
            label18.AutoSize = true;
            label18.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label18.ForeColor = Color.FromArgb(98, 116, 142);
            label18.Location = new Point(433, 590);
            label18.Name = "label18";
            label18.Size = new Size(37, 19);
            label18.TabIndex = 125;
            label18.Text = "紫色";
            // 
            // cascader12
            // 
            cascader12.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader12.ArrowSize = 8;
            cascader12.BackColor = Color.White;
            cascader12.CornerRadius = 6;
            cascader12.FillColor = Color.FromArgb(245, 245, 245);
            cascader12.FocusBorderColor = Color.FromArgb(20, 184, 166);
            cascader12.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader12.Location = new Point(48, 630);
            cascader12.Name = "cascader12";
            cascaderOption265.Label = "游仙区";
            cascaderOption265.Value = "";
            cascaderOption264.Children.Add(cascaderOption265);
            cascaderOption264.Label = "锦阳市";
            cascaderOption264.Value = "";
            cascaderOption267.Label = "青羊区";
            cascaderOption267.Value = "";
            cascaderOption268.Label = "锦江区";
            cascaderOption268.Value = "";
            cascaderOption269.Label = "武侯区";
            cascaderOption269.Value = "";
            cascaderOption266.Children.Add(cascaderOption267);
            cascaderOption266.Children.Add(cascaderOption268);
            cascaderOption266.Children.Add(cascaderOption269);
            cascaderOption266.Label = "成都市";
            cascaderOption266.Value = "";
            cascaderOption263.Children.Add(cascaderOption264);
            cascaderOption263.Children.Add(cascaderOption266);
            cascaderOption263.Label = "四川省";
            cascaderOption263.Value = "";
            cascaderOption272.Label = "越秀区";
            cascaderOption272.Value = "";
            cascaderOption273.Label = "天河区";
            cascaderOption273.Value = "";
            cascaderOption271.Children.Add(cascaderOption272);
            cascaderOption271.Children.Add(cascaderOption273);
            cascaderOption271.Label = "广州市";
            cascaderOption271.Value = "";
            cascaderOption275.Label = "福田区";
            cascaderOption275.Value = "";
            cascaderOption276.Label = "南山区";
            cascaderOption276.Value = "";
            cascaderOption274.Children.Add(cascaderOption275);
            cascaderOption274.Children.Add(cascaderOption276);
            cascaderOption274.Label = "深圳市";
            cascaderOption274.Value = "";
            cascaderOption270.Children.Add(cascaderOption271);
            cascaderOption270.Children.Add(cascaderOption274);
            cascaderOption270.Label = "广东省";
            cascaderOption270.Value = "";
            cascaderOption278.Label = "朝阳区";
            cascaderOption278.Value = "";
            cascaderOption279.Label = "海淀区";
            cascaderOption279.Value = "";
            cascaderOption277.Children.Add(cascaderOption278);
            cascaderOption277.Children.Add(cascaderOption279);
            cascaderOption277.Label = "北京市";
            cascaderOption277.Value = "";
            cascader12.Options.Add(cascaderOption263);
            cascader12.Options.Add(cascaderOption270);
            cascader12.Options.Add(cascaderOption277);
            cascader12.Placeholder = "省 / 市 / 区";
            cascader12.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader12.SelectedForeColor = Color.FromArgb(20, 184, 166);
            cascader12.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader12.Size = new Size(196, 32);
            cascader12.TabIndex = 124;
            cascader12.Text = "cascader12";
            // 
            // label19
            // 
            label19.AutoSize = true;
            label19.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label19.ForeColor = Color.FromArgb(98, 116, 142);
            label19.Location = new Point(44, 590);
            label19.Name = "label19";
            label19.Size = new Size(65, 19);
            label19.TabIndex = 123;
            label19.Text = "默认蓝色";
            // 
            // label20
            // 
            label20.AutoSize = true;
            label20.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label20.ForeColor = Color.FromArgb(30, 41, 57);
            label20.Location = new Point(39, 546);
            label20.Name = "label20";
            label20.Size = new Size(132, 26);
            label20.TabIndex = 122;
            label20.Text = "不同主题颜色";
            // 
            // cascader9
            // 
            cascader9.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader9.ArrowSize = 8;
            cascader9.BackColor = Color.White;
            cascader9.CornerRadius = 6;
            cascader9.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader9.FillColor = Color.FromArgb(245, 245, 245);
            cascader9.FocusBorderColor = Color.FromArgb(245, 158, 11);
            cascader9.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader9.Location = new Point(850, 480);
            cascader9.Name = "cascader9";
            cascaderOption282.Label = "React组";
            cascaderOption282.Value = "";
            cascaderOption283.Label = "Vue组";
            cascaderOption283.Value = "";
            cascaderOption281.Children.Add(cascaderOption282);
            cascaderOption281.Children.Add(cascaderOption283);
            cascaderOption281.Label = "前端组";
            cascaderOption281.Value = "";
            cascaderOption285.Label = "";
            cascaderOption285.Value = "";
            cascaderOption286.Label = "";
            cascaderOption286.Value = "";
            cascaderOption284.Children.Add(cascaderOption285);
            cascaderOption284.Children.Add(cascaderOption286);
            cascaderOption284.Disabled = true;
            cascaderOption284.Label = "后端组";
            cascaderOption284.Value = "";
            cascaderOption280.Children.Add(cascaderOption281);
            cascaderOption280.Children.Add(cascaderOption284);
            cascaderOption280.Label = "技术部";
            cascaderOption280.Value = "";
            cascaderOption288.Label = "产品经理";
            cascaderOption288.Value = "";
            cascaderOption289.Label = "设计师";
            cascaderOption289.Value = "";
            cascaderOption287.Children.Add(cascaderOption288);
            cascaderOption287.Children.Add(cascaderOption289);
            cascaderOption287.Label = "产品部";
            cascaderOption287.Value = "";
            cascader9.Options.Add(cascaderOption280);
            cascader9.Options.Add(cascaderOption287);
            cascader9.Placeholder = "选择部门";
            cascader9.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader9.SelectedForeColor = Color.FromArgb(245, 158, 11);
            cascader9.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader9.Size = new Size(196, 32);
            cascader9.TabIndex = 121;
            cascader9.Text = "cascader9";
            // 
            // label16
            // 
            label16.AutoSize = true;
            label16.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label16.ForeColor = Color.FromArgb(98, 116, 142);
            label16.Location = new Point(846, 440);
            label16.Name = "label16";
            label16.Size = new Size(135, 19);
            label16.TabIndex = 120;
            label16.Text = "组织架构 (含禁用项)";
            // 
            // cascader7
            // 
            cascader7.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader7.ArrowSize = 8;
            cascader7.BackColor = Color.White;
            cascader7.CornerRadius = 6;
            cascader7.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader7.FillColor = Color.FromArgb(245, 245, 245);
            cascader7.FocusBorderColor = Color.FromArgb(139, 92, 246);
            cascader7.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader7.Location = new Point(437, 480);
            cascader7.Name = "cascader7";
            cascaderOption292.Label = "Android";
            cascaderOption292.Value = "";
            cascaderOption293.Label = "IPhone";
            cascaderOption293.Value = "";
            cascaderOption291.Children.Add(cascaderOption292);
            cascaderOption291.Children.Add(cascaderOption293);
            cascaderOption291.Label = "手机";
            cascaderOption291.Value = "";
            cascaderOption295.Label = "笔记本";
            cascaderOption295.Value = "";
            cascaderOption296.Label = "台式机";
            cascaderOption296.Value = "";
            cascaderOption294.Children.Add(cascaderOption295);
            cascaderOption294.Children.Add(cascaderOption296);
            cascaderOption294.Label = "电脑";
            cascaderOption294.Value = "";
            cascaderOption290.Children.Add(cascaderOption291);
            cascaderOption290.Children.Add(cascaderOption294);
            cascaderOption290.Label = "电子产品";
            cascaderOption290.Value = "";
            cascaderOption299.Label = "半身裙";
            cascaderOption299.Value = "";
            cascaderOption300.Label = "连衣裙";
            cascaderOption300.Value = "";
            cascaderOption298.Children.Add(cascaderOption299);
            cascaderOption298.Children.Add(cascaderOption300);
            cascaderOption298.Label = "女装";
            cascaderOption298.Value = "";
            cascaderOption302.Label = "牛仔裤";
            cascaderOption302.Value = "";
            cascaderOption303.Label = "T恤";
            cascaderOption303.Value = "";
            cascaderOption301.Children.Add(cascaderOption302);
            cascaderOption301.Children.Add(cascaderOption303);
            cascaderOption301.Label = "男装";
            cascaderOption301.Value = "";
            cascaderOption297.Children.Add(cascaderOption298);
            cascaderOption297.Children.Add(cascaderOption301);
            cascaderOption297.Label = "服装";
            cascaderOption297.Value = "";
            cascader7.Options.Add(cascaderOption290);
            cascader7.Options.Add(cascaderOption297);
            cascader7.Placeholder = "选择分类";
            cascader7.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader7.SelectedForeColor = Color.FromArgb(139, 92, 246);
            cascader7.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader7.Size = new Size(196, 32);
            cascader7.TabIndex = 119;
            cascader7.Text = "cascader7";
            // 
            // label10
            // 
            label10.AutoSize = true;
            label10.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label10.ForeColor = Color.FromArgb(98, 116, 142);
            label10.Location = new Point(433, 440);
            label10.Name = "label10";
            label10.Size = new Size(65, 19);
            label10.TabIndex = 118;
            label10.Text = "商品分类";
            // 
            // cascader8
            // 
            cascader8.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader8.ArrowSize = 8;
            cascader8.BackColor = Color.White;
            cascader8.CornerRadius = 6;
            cascader8.FillColor = Color.FromArgb(245, 245, 245);
            cascader8.FocusBorderColor = Color.FromArgb(20, 184, 166);
            cascader8.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader8.Location = new Point(48, 480);
            cascader8.Name = "cascader8";
            cascaderOption306.Label = "游仙区";
            cascaderOption306.Value = "";
            cascaderOption305.Children.Add(cascaderOption306);
            cascaderOption305.Label = "锦阳市";
            cascaderOption305.Value = "";
            cascaderOption308.Label = "青羊区";
            cascaderOption308.Value = "";
            cascaderOption309.Label = "锦江区";
            cascaderOption309.Value = "";
            cascaderOption310.Label = "武侯区";
            cascaderOption310.Value = "";
            cascaderOption307.Children.Add(cascaderOption308);
            cascaderOption307.Children.Add(cascaderOption309);
            cascaderOption307.Children.Add(cascaderOption310);
            cascaderOption307.Label = "成都市";
            cascaderOption307.Value = "";
            cascaderOption304.Children.Add(cascaderOption305);
            cascaderOption304.Children.Add(cascaderOption307);
            cascaderOption304.Label = "四川省";
            cascaderOption304.Value = "";
            cascaderOption313.Label = "越秀区";
            cascaderOption313.Value = "";
            cascaderOption314.Label = "天河区";
            cascaderOption314.Value = "";
            cascaderOption312.Children.Add(cascaderOption313);
            cascaderOption312.Children.Add(cascaderOption314);
            cascaderOption312.Label = "广州市";
            cascaderOption312.Value = "";
            cascaderOption316.Label = "福田区";
            cascaderOption316.Value = "";
            cascaderOption317.Label = "南山区";
            cascaderOption317.Value = "";
            cascaderOption315.Children.Add(cascaderOption316);
            cascaderOption315.Children.Add(cascaderOption317);
            cascaderOption315.Label = "深圳市";
            cascaderOption315.Value = "";
            cascaderOption311.Children.Add(cascaderOption312);
            cascaderOption311.Children.Add(cascaderOption315);
            cascaderOption311.Label = "广东省";
            cascaderOption311.Value = "";
            cascaderOption319.Label = "朝阳区";
            cascaderOption319.Value = "";
            cascaderOption320.Label = "海淀区";
            cascaderOption320.Value = "";
            cascaderOption318.Children.Add(cascaderOption319);
            cascaderOption318.Children.Add(cascaderOption320);
            cascaderOption318.Label = "北京市";
            cascaderOption318.Value = "";
            cascader8.Options.Add(cascaderOption304);
            cascader8.Options.Add(cascaderOption311);
            cascader8.Options.Add(cascaderOption318);
            cascader8.Placeholder = "省 / 市 / 区";
            cascader8.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader8.SelectedForeColor = Color.FromArgb(20, 184, 166);
            cascader8.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader8.Size = new Size(196, 32);
            cascader8.TabIndex = 117;
            cascader8.Text = "cascader8";
            // 
            // label12
            // 
            label12.AutoSize = true;
            label12.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label12.ForeColor = Color.FromArgb(98, 116, 142);
            label12.Location = new Point(44, 440);
            label12.Name = "label12";
            label12.Size = new Size(65, 19);
            label12.TabIndex = 116;
            label12.Text = "地区选择";
            // 
            // label15
            // 
            label15.AutoSize = true;
            label15.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label15.ForeColor = Color.FromArgb(30, 41, 57);
            label15.Location = new Point(39, 396);
            label15.Name = "label15";
            label15.Size = new Size(132, 26);
            label15.TabIndex = 115;
            label15.Text = "不同数据类型";
            // 
            // cascader6
            // 
            cascader6.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader6.ArrowSize = 8;
            cascader6.BackColor = Color.White;
            cascader6.CornerRadius = 6;
            cascader6.DisplayMode = LYHControls.CascaderDisplayMode.Last;
            cascader6.FillColor = Color.FromArgb(245, 245, 245);
            cascader6.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader6.Location = new Point(437, 332);
            cascader6.Name = "cascader6";
            cascaderOption323.Label = "游仙区";
            cascaderOption323.Value = "";
            cascaderOption322.Children.Add(cascaderOption323);
            cascaderOption322.Label = "锦阳市";
            cascaderOption322.Value = "";
            cascaderOption325.Label = "青羊区";
            cascaderOption325.Value = "";
            cascaderOption326.Label = "锦江区";
            cascaderOption326.Value = "";
            cascaderOption327.Label = "武侯区";
            cascaderOption327.Value = "";
            cascaderOption324.Children.Add(cascaderOption325);
            cascaderOption324.Children.Add(cascaderOption326);
            cascaderOption324.Children.Add(cascaderOption327);
            cascaderOption324.Label = "成都市";
            cascaderOption324.Value = "";
            cascaderOption321.Children.Add(cascaderOption322);
            cascaderOption321.Children.Add(cascaderOption324);
            cascaderOption321.Label = "四川省";
            cascaderOption321.Value = "";
            cascaderOption330.Label = "越秀区";
            cascaderOption330.Value = "";
            cascaderOption331.Label = "天河区";
            cascaderOption331.Value = "";
            cascaderOption329.Children.Add(cascaderOption330);
            cascaderOption329.Children.Add(cascaderOption331);
            cascaderOption329.Label = "广州市";
            cascaderOption329.Value = "";
            cascaderOption333.Label = "福田区";
            cascaderOption333.Value = "";
            cascaderOption334.Label = "南山区";
            cascaderOption334.Value = "";
            cascaderOption332.Children.Add(cascaderOption333);
            cascaderOption332.Children.Add(cascaderOption334);
            cascaderOption332.Label = "深圳市";
            cascaderOption332.Value = "";
            cascaderOption328.Children.Add(cascaderOption329);
            cascaderOption328.Children.Add(cascaderOption332);
            cascaderOption328.Label = "广东省";
            cascaderOption328.Value = "";
            cascaderOption336.Label = "朝阳区";
            cascaderOption336.Value = "";
            cascaderOption337.Label = "海淀区";
            cascaderOption337.Value = "";
            cascaderOption335.Children.Add(cascaderOption336);
            cascaderOption335.Children.Add(cascaderOption337);
            cascaderOption335.Label = "北京市";
            cascaderOption335.Value = "";
            cascader6.Options.Add(cascaderOption321);
            cascader6.Options.Add(cascaderOption328);
            cascader6.Options.Add(cascaderOption335);
            cascader6.Placeholder = "仅显示最后一级";
            cascader6.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader6.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader6.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader6.Size = new Size(196, 32);
            cascader6.TabIndex = 114;
            cascader6.Text = "cascader6";
            // 
            // label9
            // 
            label9.AutoSize = true;
            label9.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label9.ForeColor = Color.FromArgb(98, 116, 142);
            label9.Location = new Point(433, 292);
            label9.Name = "label9";
            label9.Size = new Size(107, 19);
            label9.TabIndex = 113;
            label9.Text = "Last - 最后一级";
            // 
            // cascader5
            // 
            cascader5.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader5.ArrowSize = 8;
            cascader5.BackColor = Color.White;
            cascader5.CornerRadius = 6;
            cascader5.FillColor = Color.FromArgb(245, 245, 245);
            cascader5.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader5.Location = new Point(48, 332);
            cascader5.Name = "cascader5";
            cascaderOption340.Label = "游仙区";
            cascaderOption340.Value = "";
            cascaderOption339.Children.Add(cascaderOption340);
            cascaderOption339.Label = "锦阳市";
            cascaderOption339.Value = "";
            cascaderOption342.Label = "青羊区";
            cascaderOption342.Value = "";
            cascaderOption343.Label = "锦江区";
            cascaderOption343.Value = "";
            cascaderOption344.Label = "武侯区";
            cascaderOption344.Value = "";
            cascaderOption341.Children.Add(cascaderOption342);
            cascaderOption341.Children.Add(cascaderOption343);
            cascaderOption341.Children.Add(cascaderOption344);
            cascaderOption341.Label = "成都市";
            cascaderOption341.Value = "";
            cascaderOption338.Children.Add(cascaderOption339);
            cascaderOption338.Children.Add(cascaderOption341);
            cascaderOption338.Label = "四川省";
            cascaderOption338.Value = "";
            cascaderOption347.Label = "越秀区";
            cascaderOption347.Value = "";
            cascaderOption348.Label = "天河区";
            cascaderOption348.Value = "";
            cascaderOption346.Children.Add(cascaderOption347);
            cascaderOption346.Children.Add(cascaderOption348);
            cascaderOption346.Label = "广州市";
            cascaderOption346.Value = "";
            cascaderOption350.Label = "福田区";
            cascaderOption350.Value = "";
            cascaderOption351.Label = "南山区";
            cascaderOption351.Value = "";
            cascaderOption349.Children.Add(cascaderOption350);
            cascaderOption349.Children.Add(cascaderOption351);
            cascaderOption349.Label = "深圳市";
            cascaderOption349.Value = "";
            cascaderOption345.Children.Add(cascaderOption346);
            cascaderOption345.Children.Add(cascaderOption349);
            cascaderOption345.Label = "广东省";
            cascaderOption345.Value = "";
            cascaderOption353.Label = "朝阳区";
            cascaderOption353.Value = "";
            cascaderOption354.Label = "海淀区";
            cascaderOption354.Value = "";
            cascaderOption352.Children.Add(cascaderOption353);
            cascaderOption352.Children.Add(cascaderOption354);
            cascaderOption352.Label = "北京市";
            cascaderOption352.Value = "";
            cascader5.Options.Add(cascaderOption338);
            cascader5.Options.Add(cascaderOption345);
            cascader5.Options.Add(cascaderOption352);
            cascader5.Placeholder = "显示完整路径";
            cascader5.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader5.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader5.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader5.Size = new Size(196, 32);
            cascader5.TabIndex = 112;
            cascader5.Text = "cascader5";
            // 
            // cascader4
            // 
            cascader4.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader4.ArrowSize = 8;
            cascader4.BackColor = Color.White;
            cascader4.CornerRadius = 6;
            cascader4.FillColor = Color.FromArgb(245, 245, 245);
            cascader4.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader4.Location = new Point(1272, 183);
            cascader4.Name = "cascader4";
            cascaderOption357.Label = "游仙区";
            cascaderOption357.Value = "";
            cascaderOption356.Children.Add(cascaderOption357);
            cascaderOption356.Label = "锦阳市";
            cascaderOption356.Value = "";
            cascaderOption359.Label = "青羊区";
            cascaderOption359.Value = "";
            cascaderOption360.Label = "锦江区";
            cascaderOption360.Value = "";
            cascaderOption361.Label = "武侯区";
            cascaderOption361.Value = "";
            cascaderOption358.Children.Add(cascaderOption359);
            cascaderOption358.Children.Add(cascaderOption360);
            cascaderOption358.Children.Add(cascaderOption361);
            cascaderOption358.Label = "成都市";
            cascaderOption358.Value = "";
            cascaderOption355.Children.Add(cascaderOption356);
            cascaderOption355.Children.Add(cascaderOption358);
            cascaderOption355.Label = "四川省";
            cascaderOption355.Value = "";
            cascaderOption364.Label = "越秀区";
            cascaderOption364.Value = "";
            cascaderOption365.Label = "天河区";
            cascaderOption365.Value = "";
            cascaderOption363.Children.Add(cascaderOption364);
            cascaderOption363.Children.Add(cascaderOption365);
            cascaderOption363.Label = "广州市";
            cascaderOption363.Value = "";
            cascaderOption367.Label = "福田区";
            cascaderOption367.Value = "";
            cascaderOption368.Label = "南山区";
            cascaderOption368.Value = "";
            cascaderOption366.Children.Add(cascaderOption367);
            cascaderOption366.Children.Add(cascaderOption368);
            cascaderOption366.Label = "深圳市";
            cascaderOption366.Value = "";
            cascaderOption362.Children.Add(cascaderOption363);
            cascaderOption362.Children.Add(cascaderOption366);
            cascaderOption362.Label = "广东省";
            cascaderOption362.Value = "";
            cascaderOption370.Label = "朝阳区";
            cascaderOption370.Value = "";
            cascaderOption371.Label = "海淀区";
            cascaderOption371.Value = "";
            cascaderOption369.Children.Add(cascaderOption370);
            cascaderOption369.Children.Add(cascaderOption371);
            cascaderOption369.Label = "北京市";
            cascaderOption369.Value = "";
            cascader4.Options.Add(cascaderOption355);
            cascader4.Options.Add(cascaderOption362);
            cascader4.Options.Add(cascaderOption369);
            cascader4.Placeholder = "选择地区";
            cascader4.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader4.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader4.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader4.Size = new Size(196, 32);
            cascader4.TabIndex = 111;
            cascader4.Text = "cascader4";
            cascader4.Variant = LYHControls.CascaderVariant.Underlined;
            // 
            // cascader3
            // 
            cascader3.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader3.ArrowSize = 8;
            cascader3.BackColor = Color.White;
            cascader3.CornerRadius = 6;
            cascader3.FillColor = Color.FromArgb(245, 245, 245);
            cascader3.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader3.Location = new Point(850, 183);
            cascader3.Name = "cascader3";
            cascaderOption374.Label = "游仙区";
            cascaderOption374.Value = "";
            cascaderOption373.Children.Add(cascaderOption374);
            cascaderOption373.Label = "锦阳市";
            cascaderOption373.Value = "";
            cascaderOption376.Label = "青羊区";
            cascaderOption376.Value = "";
            cascaderOption377.Label = "锦江区";
            cascaderOption377.Value = "";
            cascaderOption378.Label = "武侯区";
            cascaderOption378.Value = "";
            cascaderOption375.Children.Add(cascaderOption376);
            cascaderOption375.Children.Add(cascaderOption377);
            cascaderOption375.Children.Add(cascaderOption378);
            cascaderOption375.Label = "成都市";
            cascaderOption375.Value = "";
            cascaderOption372.Children.Add(cascaderOption373);
            cascaderOption372.Children.Add(cascaderOption375);
            cascaderOption372.Label = "四川省";
            cascaderOption372.Value = "";
            cascaderOption381.Label = "越秀区";
            cascaderOption381.Value = "";
            cascaderOption382.Label = "天河区";
            cascaderOption382.Value = "";
            cascaderOption380.Children.Add(cascaderOption381);
            cascaderOption380.Children.Add(cascaderOption382);
            cascaderOption380.Label = "广州市";
            cascaderOption380.Value = "";
            cascaderOption384.Label = "福田区";
            cascaderOption384.Value = "";
            cascaderOption385.Label = "南山区";
            cascaderOption385.Value = "";
            cascaderOption383.Children.Add(cascaderOption384);
            cascaderOption383.Children.Add(cascaderOption385);
            cascaderOption383.Label = "深圳市";
            cascaderOption383.Value = "";
            cascaderOption379.Children.Add(cascaderOption380);
            cascaderOption379.Children.Add(cascaderOption383);
            cascaderOption379.Label = "广东省";
            cascaderOption379.Value = "";
            cascaderOption387.Label = "朝阳区";
            cascaderOption387.Value = "";
            cascaderOption388.Label = "海淀区";
            cascaderOption388.Value = "";
            cascaderOption386.Children.Add(cascaderOption387);
            cascaderOption386.Children.Add(cascaderOption388);
            cascaderOption386.Label = "北京市";
            cascaderOption386.Value = "";
            cascader3.Options.Add(cascaderOption372);
            cascader3.Options.Add(cascaderOption379);
            cascader3.Options.Add(cascaderOption386);
            cascader3.Placeholder = "选择地区";
            cascader3.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader3.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader3.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader3.Size = new Size(196, 32);
            cascader3.TabIndex = 110;
            cascader3.Text = "cascader3";
            cascader3.Variant = LYHControls.CascaderVariant.Borderless;
            // 
            // cascader2
            // 
            cascader2.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader2.ArrowSize = 8;
            cascader2.BackColor = Color.White;
            cascader2.CornerRadius = 6;
            cascader2.FillColor = Color.FromArgb(245, 245, 245);
            cascader2.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader2.Location = new Point(437, 183);
            cascader2.Name = "cascader2";
            cascaderOption391.Label = "游仙区";
            cascaderOption391.Value = "";
            cascaderOption390.Children.Add(cascaderOption391);
            cascaderOption390.Label = "锦阳市";
            cascaderOption390.Value = "";
            cascaderOption393.Label = "青羊区";
            cascaderOption393.Value = "";
            cascaderOption394.Label = "锦江区";
            cascaderOption394.Value = "";
            cascaderOption395.Label = "武侯区";
            cascaderOption395.Value = "";
            cascaderOption392.Children.Add(cascaderOption393);
            cascaderOption392.Children.Add(cascaderOption394);
            cascaderOption392.Children.Add(cascaderOption395);
            cascaderOption392.Label = "成都市";
            cascaderOption392.Value = "";
            cascaderOption389.Children.Add(cascaderOption390);
            cascaderOption389.Children.Add(cascaderOption392);
            cascaderOption389.Label = "四川省";
            cascaderOption389.Value = "";
            cascaderOption398.Label = "越秀区";
            cascaderOption398.Value = "";
            cascaderOption399.Label = "天河区";
            cascaderOption399.Value = "";
            cascaderOption397.Children.Add(cascaderOption398);
            cascaderOption397.Children.Add(cascaderOption399);
            cascaderOption397.Label = "广州市";
            cascaderOption397.Value = "";
            cascaderOption401.Label = "福田区";
            cascaderOption401.Value = "";
            cascaderOption402.Label = "南山区";
            cascaderOption402.Value = "";
            cascaderOption400.Children.Add(cascaderOption401);
            cascaderOption400.Children.Add(cascaderOption402);
            cascaderOption400.Label = "深圳市";
            cascaderOption400.Value = "";
            cascaderOption396.Children.Add(cascaderOption397);
            cascaderOption396.Children.Add(cascaderOption400);
            cascaderOption396.Label = "广东省";
            cascaderOption396.Value = "";
            cascaderOption404.Label = "朝阳区";
            cascaderOption404.Value = "";
            cascaderOption405.Label = "海淀区";
            cascaderOption405.Value = "";
            cascaderOption403.Children.Add(cascaderOption404);
            cascaderOption403.Children.Add(cascaderOption405);
            cascaderOption403.Label = "北京市";
            cascaderOption403.Value = "";
            cascader2.Options.Add(cascaderOption389);
            cascader2.Options.Add(cascaderOption396);
            cascader2.Options.Add(cascaderOption403);
            cascader2.Placeholder = "选择地区";
            cascader2.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader2.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader2.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader2.Size = new Size(196, 32);
            cascader2.TabIndex = 109;
            cascader2.Text = "cascader2";
            cascader2.Variant = LYHControls.CascaderVariant.Filled;
            // 
            // label7
            // 
            label7.AutoSize = true;
            label7.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label7.ForeColor = Color.FromArgb(98, 116, 142);
            label7.Location = new Point(44, 292);
            label7.Name = "label7";
            label7.Size = new Size(95, 19);
            label7.TabIndex = 108;
            label7.Text = "All - 完整路径";
            // 
            // label8
            // 
            label8.AutoSize = true;
            label8.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label8.ForeColor = Color.FromArgb(30, 41, 57);
            label8.Location = new Point(39, 248);
            label8.Name = "label8";
            label8.Size = new Size(92, 26);
            label8.TabIndex = 107;
            label8.Text = "显示模式";
            // 
            // cascader1
            // 
            cascader1.ArrowColor = Color.FromArgb(140, 140, 140);
            cascader1.ArrowSize = 8;
            cascader1.BackColor = Color.White;
            cascader1.CornerRadius = 6;
            cascader1.FillColor = Color.FromArgb(245, 245, 245);
            cascader1.Font = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader1.Location = new Point(48, 183);
            cascader1.Name = "cascader1";
            cascaderOption408.Label = "游仙区";
            cascaderOption408.Value = "";
            cascaderOption407.Children.Add(cascaderOption408);
            cascaderOption407.Label = "锦阳市";
            cascaderOption407.Value = "";
            cascaderOption410.Label = "青羊区";
            cascaderOption410.Value = "";
            cascaderOption411.Label = "锦江区";
            cascaderOption411.Value = "";
            cascaderOption412.Label = "武侯区";
            cascaderOption412.Value = "";
            cascaderOption409.Children.Add(cascaderOption410);
            cascaderOption409.Children.Add(cascaderOption411);
            cascaderOption409.Children.Add(cascaderOption412);
            cascaderOption409.Label = "成都市";
            cascaderOption409.Value = "";
            cascaderOption406.Children.Add(cascaderOption407);
            cascaderOption406.Children.Add(cascaderOption409);
            cascaderOption406.Label = "四川省";
            cascaderOption406.Value = "";
            cascaderOption415.Label = "越秀区";
            cascaderOption415.Value = "";
            cascaderOption416.Label = "天河区";
            cascaderOption416.Value = "";
            cascaderOption414.Children.Add(cascaderOption415);
            cascaderOption414.Children.Add(cascaderOption416);
            cascaderOption414.Label = "广州市";
            cascaderOption414.Value = "";
            cascaderOption418.Label = "福田区";
            cascaderOption418.Value = "";
            cascaderOption419.Label = "南山区";
            cascaderOption419.Value = "";
            cascaderOption417.Children.Add(cascaderOption418);
            cascaderOption417.Children.Add(cascaderOption419);
            cascaderOption417.Label = "深圳市";
            cascaderOption417.Value = "";
            cascaderOption413.Children.Add(cascaderOption414);
            cascaderOption413.Children.Add(cascaderOption417);
            cascaderOption413.Label = "广东省";
            cascaderOption413.Value = "";
            cascaderOption421.Label = "朝阳区";
            cascaderOption421.Value = "";
            cascaderOption422.Label = "海淀区";
            cascaderOption422.Value = "";
            cascaderOption420.Children.Add(cascaderOption421);
            cascaderOption420.Children.Add(cascaderOption422);
            cascaderOption420.Label = "北京市";
            cascaderOption420.Value = "";
            cascader1.Options.Add(cascaderOption406);
            cascader1.Options.Add(cascaderOption413);
            cascader1.Options.Add(cascaderOption420);
            cascader1.Placeholder = "选择地区";
            cascader1.SelectedFont = new Font("HarmonyOS Sans SC", 9F, FontStyle.Regular, GraphicsUnit.Point, 134);
            cascader1.SelectedForeColor = Color.FromArgb(22, 119, 255);
            cascader1.SeparatorColor = Color.FromArgb(220, 220, 220);
            cascader1.Size = new Size(196, 32);
            cascader1.TabIndex = 103;
            cascader1.Text = "cascader1";
            // 
            // label6
            // 
            label6.AutoSize = true;
            label6.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label6.ForeColor = Color.FromArgb(98, 116, 142);
            label6.Location = new Point(1272, 144);
            label6.Name = "label6";
            label6.Size = new Size(136, 19);
            label6.TabIndex = 102;
            label6.Text = "Underlined (下划线)";
            // 
            // label4
            // 
            label4.AutoSize = true;
            label4.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label4.ForeColor = Color.FromArgb(98, 116, 142);
            label4.Location = new Point(850, 144);
            label4.Name = "label4";
            label4.Size = new Size(132, 19);
            label4.TabIndex = 100;
            label4.Text = "Borderless (无边框)";
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label3.ForeColor = Color.FromArgb(98, 116, 142);
            label3.Location = new Point(437, 144);
            label3.Name = "label3";
            label3.Size = new Size(99, 19);
            label3.TabIndex = 98;
            label3.Text = "Filled (填充型)";
            // 
            // label5
            // 
            label5.AutoSize = true;
            label5.Font = new Font("HarmonyOS Sans SC", 10F, FontStyle.Regular, GraphicsUnit.Point, 134);
            label5.ForeColor = Color.FromArgb(98, 116, 142);
            label5.Location = new Point(44, 144);
            label5.Name = "label5";
            label5.Size = new Size(120, 19);
            label5.TabIndex = 96;
            label5.Text = "Outlined (描边型)";
            // 
            // label13
            // 
            label13.AutoSize = true;
            label13.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label13.ForeColor = Color.FromArgb(30, 41, 57);
            label13.Location = new Point(35, 346);
            label13.Name = "label13";
            label13.Size = new Size(17, 26);
            label13.TabIndex = 67;
            label13.Text = " ";
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Font = new Font("HarmonyOS Sans SC", 20F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label1.ForeColor = Color.FromArgb(30, 41, 57);
            label1.Location = new Point(39, 100);
            label1.Name = "label1";
            label1.Size = new Size(132, 26);
            label1.TabIndex = 5;
            label1.Text = "四种外观变体";
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(243, 244, 246);
            panel1.Controls.Add(label14);
            panel1.Controls.Add(label11);
            panel1.Controls.Add(label2);
            panel1.Location = new Point(1, 1);
            panel1.Name = "panel1";
            panel1.Size = new Size(1628, 79);
            panel1.TabIndex = 0;
            // 
            // label14
            // 
            label14.Font = new Font("HarmonyOS Sans SC", 18F, FontStyle.Regular, GraphicsUnit.Pixel, 134);
            label14.ForeColor = Color.FromArgb(74, 85, 101);
            label14.Location = new Point(38, 43);
            label14.Name = "label14";
            label14.Size = new Size(653, 25);
            label14.TabIndex = 7;
            label14.Text = "支持多种日期类型、4种外观变体和丰富的交互效果";
            // 
            // label11
            // 
            label11.AutoSize = true;
            label11.Font = new Font("HarmonyOS Sans SC", 26F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label11.ForeColor = Color.FromArgb(30, 41, 57);
            label11.Location = new Point(37, 8);
            label11.Name = "label11";
            label11.Size = new Size(287, 34);
            label11.TabIndex = 6;
            label11.Text = "DatePicker 日期选择器";
            // 
            // label2
            // 
            label2.BackColor = Color.FromArgb(209, 213, 220);
            label2.Location = new Point(0, 78);
            label2.Name = "label2";
            label2.Size = new Size(1628, 2);
            label2.TabIndex = 3;
            label2.Text = "label2";
            // 
            // Cascader
            // 
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(smoothScrollPanel1);
            Name = "Cascader";
            Size = new Size(1700, 990);
            smoothScrollPanel1.ResumeLayout(false);
            smoothScrollPanel2.ResumeLayout(false);
            smoothScrollPanel2.PerformLayout();
            smoothScrollPanel3.ResumeLayout(false);
            smoothScrollPanel3.PerformLayout();
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private SmoothScrollPanel smoothScrollPanel1;
        private SmoothScrollPanel smoothScrollPanel2;
        private Label label13;
        private Panel panel1;
        private Label label14;
        private Label label11;
        private Label label2;
        private Label label3;
        private Label label5;
        private Label label1;
        private Label label6;
        private Label label4;
        private LYHControls.Cascader cascader1;
        private Label label7;
        private Label label8;
        private LYHControls.Cascader cascader4;
        private LYHControls.Cascader cascader3;
        private LYHControls.Cascader cascader2;
        private LYHControls.Cascader cascader5;
        private LYHControls.Cascader cascader6;
        private Label label9;
        private LYHControls.Cascader cascader7;
        private Label label10;
        private LYHControls.Cascader cascader8;
        private Label label12;
        private Label label15;
        private LYHControls.Cascader cascader9;
        private Label label16;
        private LYHControls.Cascader cascader10;
        private Label label17;
        private LYHControls.Cascader cascader11;
        private Label label18;
        private LYHControls.Cascader cascader12;
        private Label label19;
        private Label label20;
        private LYHControls.SmoothScrollPanel smoothScrollPanel3;
        private LYHControls.Multi_funcButton multi_funcButton1;
        private Label label23;
        private Label label27;
        private Label label29;
        private LYHControls.Cascader cascader13;
        private LYHControls.InputText inputText1;
        private LYHControls.Cascader cascader14;
        private Label label21;
    }
}
