namespace Save_HMI_Controls
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            LYHControls.LYHMenuItem lyhMenuItem1 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem2 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem3 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem4 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem5 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem6 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem7 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem8 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem9 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem10 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem11 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem12 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem13 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem14 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem15 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem16 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem17 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem18 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem19 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem20 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem21 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem22 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem23 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem24 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem25 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem26 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem27 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem28 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem29 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem30 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem31 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem32 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem33 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem34 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem35 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem36 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem37 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem38 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem39 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem40 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem41 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem42 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem43 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem44 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem45 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem46 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem47 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem48 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem49 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem50 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem51 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem52 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem53 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem54 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem55 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem56 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem57 = new LYHControls.LYHMenuItem();
            LYHControls.LYHMenuItem lyhMenuItem58 = new LYHControls.LYHMenuItem();
            treeMenu1 = new LYHControls.TreeMenu();
            mainwindow = new Panel();
            panel1 = new Panel();
            label2 = new Label();
            label1 = new Label();
            pictureBox1 = new PictureBox();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            SuspendLayout();
            // 
            // treeMenu1
            // 
            treeMenu1.BackColor = Color.FromArgb(0, 62, 164);
            treeMenu1.DefaultSelectedIndex = 0;
            treeMenu1.Font = new Font("HarmonyOS Sans SC", 15F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            treeMenu1.ForeColor = Color.Silver;
            treeMenu1.IconLeftMargin = 30;
            treeMenu1.IconSize = 18;
            treeMenu1.IconTextSpacing = 5;
            treeMenu1.IsDarkTheme = false;
            lyhMenuItem1.BadgeText = "";
            lyhMenuItem1.Enabled = true;
            lyhMenuItem1.Icon = null;
            lyhMenuItem1.IsExpanded = false;
            lyhMenuItem1.ItemBackColor = Color.Empty;
            lyhMenuItem1.ItemFont = new Font("HarmonyOS Sans SC", 15F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            lyhMenuItem1.ItemForeColor = Color.White;
            lyhMenuItem1.TargetPageName = "Introduction";
            lyhMenuItem1.Text = "介绍";
            lyhMenuItem2.BadgeText = "";
            lyhMenuItem2.Enabled = true;
            lyhMenuItem2.Icon = Properties.Resources.Frame1;
            lyhMenuItem2.IsExpanded = false;
            lyhMenuItem2.ItemBackColor = Color.Empty;
            lyhMenuItem2.ItemForeColor = Color.White;
            lyhMenuItem3.BadgeText = "";
            lyhMenuItem3.Enabled = true;
            lyhMenuItem3.Icon = null;
            lyhMenuItem3.IsExpanded = false;
            lyhMenuItem3.ItemBackColor = Color.Empty;
            lyhMenuItem3.ItemForeColor = Color.White;
            lyhMenuItem4.BadgeText = "";
            lyhMenuItem4.Enabled = true;
            lyhMenuItem4.Icon = null;
            lyhMenuItem4.IsExpanded = false;
            lyhMenuItem4.ItemBackColor = Color.Empty;
            lyhMenuItem4.ItemForeColor = Color.White;
            lyhMenuItem4.TargetPageName = "Button_Group";
            lyhMenuItem4.Text = "按钮组";
            lyhMenuItem5.BadgeText = "";
            lyhMenuItem5.Enabled = true;
            lyhMenuItem5.Icon = null;
            lyhMenuItem5.IsExpanded = false;
            lyhMenuItem5.ItemBackColor = Color.Empty;
            lyhMenuItem5.ItemForeColor = Color.White;
            lyhMenuItem5.TargetPageName = "DropDowm_button";
            lyhMenuItem5.Text = "下拉菜单按钮";
            lyhMenuItem6.BadgeText = "";
            lyhMenuItem6.Enabled = true;
            lyhMenuItem6.Icon = null;
            lyhMenuItem6.IsExpanded = false;
            lyhMenuItem6.ItemBackColor = Color.Empty;
            lyhMenuItem6.ItemForeColor = Color.White;
            lyhMenuItem6.TargetPageName = "Muti_func_button";
            lyhMenuItem6.Text = "多功能按钮";
            lyhMenuItem7.BadgeText = "";
            lyhMenuItem7.Enabled = true;
            lyhMenuItem7.Icon = null;
            lyhMenuItem7.IsExpanded = false;
            lyhMenuItem7.ItemBackColor = Color.Empty;
            lyhMenuItem7.ItemForeColor = Color.White;
            lyhMenuItem7.TargetPageName = "Switch_button";
            lyhMenuItem7.Text = "开关切换按钮";
            lyhMenuItem3.SubItems.Add(lyhMenuItem4);
            lyhMenuItem3.SubItems.Add(lyhMenuItem5);
            lyhMenuItem3.SubItems.Add(lyhMenuItem6);
            lyhMenuItem3.SubItems.Add(lyhMenuItem7);
            lyhMenuItem3.TargetPageName = "";
            lyhMenuItem3.Text = "按钮家族";
            lyhMenuItem8.BadgeText = "";
            lyhMenuItem8.Enabled = true;
            lyhMenuItem8.Icon = null;
            lyhMenuItem8.IsExpanded = false;
            lyhMenuItem8.ItemBackColor = Color.Empty;
            lyhMenuItem8.ItemForeColor = Color.White;
            lyhMenuItem9.BadgeText = "";
            lyhMenuItem9.Enabled = true;
            lyhMenuItem9.Icon = null;
            lyhMenuItem9.IsExpanded = false;
            lyhMenuItem9.ItemBackColor = Color.Empty;
            lyhMenuItem9.ItemForeColor = Color.White;
            lyhMenuItem9.TargetPageName = "CheckBox";
            lyhMenuItem9.Text = "单/复选框";
            lyhMenuItem10.BadgeText = "";
            lyhMenuItem10.Enabled = true;
            lyhMenuItem10.Icon = null;
            lyhMenuItem10.IsExpanded = false;
            lyhMenuItem10.ItemBackColor = Color.Empty;
            lyhMenuItem10.ItemForeColor = Color.White;
            lyhMenuItem10.TargetPageName = "Divider";
            lyhMenuItem10.Text = "分割线";
            lyhMenuItem8.SubItems.Add(lyhMenuItem9);
            lyhMenuItem8.SubItems.Add(lyhMenuItem10);
            lyhMenuItem8.TargetPageName = "";
            lyhMenuItem8.Text = "基础反馈";
            lyhMenuItem2.SubItems.Add(lyhMenuItem3);
            lyhMenuItem2.SubItems.Add(lyhMenuItem8);
            lyhMenuItem2.TargetPageName = "";
            lyhMenuItem2.Text = "基础组件与按钮";
            lyhMenuItem11.BadgeText = "";
            lyhMenuItem11.Enabled = true;
            lyhMenuItem11.Icon = Properties.Resources.Frame__1_1;
            lyhMenuItem11.IsExpanded = false;
            lyhMenuItem11.ItemBackColor = Color.Empty;
            lyhMenuItem11.ItemForeColor = Color.White;
            lyhMenuItem12.BadgeText = "";
            lyhMenuItem12.Enabled = true;
            lyhMenuItem12.Icon = null;
            lyhMenuItem12.IsExpanded = false;
            lyhMenuItem12.ItemBackColor = Color.Empty;
            lyhMenuItem12.ItemForeColor = Color.White;
            lyhMenuItem13.BadgeText = "";
            lyhMenuItem13.Enabled = true;
            lyhMenuItem13.Icon = null;
            lyhMenuItem13.IsExpanded = false;
            lyhMenuItem13.ItemBackColor = Color.Empty;
            lyhMenuItem13.ItemForeColor = Color.White;
            lyhMenuItem13.TargetPageName = "InputText";
            lyhMenuItem13.Text = "文本输入框";
            lyhMenuItem14.BadgeText = "";
            lyhMenuItem14.Enabled = true;
            lyhMenuItem14.Icon = null;
            lyhMenuItem14.IsExpanded = false;
            lyhMenuItem14.ItemBackColor = Color.Empty;
            lyhMenuItem14.ItemForeColor = Color.White;
            lyhMenuItem14.TargetPageName = "InputNumber";
            lyhMenuItem14.Text = "数字输入框";
            lyhMenuItem15.BadgeText = "";
            lyhMenuItem15.Enabled = true;
            lyhMenuItem15.Icon = null;
            lyhMenuItem15.IsExpanded = false;
            lyhMenuItem15.ItemBackColor = Color.Empty;
            lyhMenuItem15.ItemForeColor = Color.White;
            lyhMenuItem15.TargetPageName = "Slider";
            lyhMenuItem15.Text = "滑动数值输入";
            lyhMenuItem12.SubItems.Add(lyhMenuItem13);
            lyhMenuItem12.SubItems.Add(lyhMenuItem14);
            lyhMenuItem12.SubItems.Add(lyhMenuItem15);
            lyhMenuItem12.TargetPageName = "";
            lyhMenuItem12.Text = "文本与数值";
            lyhMenuItem16.BadgeText = "";
            lyhMenuItem16.Enabled = true;
            lyhMenuItem16.Icon = null;
            lyhMenuItem16.IsExpanded = false;
            lyhMenuItem16.ItemBackColor = Color.Empty;
            lyhMenuItem16.ItemForeColor = Color.White;
            lyhMenuItem17.BadgeText = "";
            lyhMenuItem17.Enabled = true;
            lyhMenuItem17.Icon = null;
            lyhMenuItem17.IsExpanded = false;
            lyhMenuItem17.ItemBackColor = Color.Empty;
            lyhMenuItem17.ItemForeColor = Color.White;
            lyhMenuItem17.TargetPageName = "DatePicker";
            lyhMenuItem17.Text = "日期选择器";
            lyhMenuItem18.BadgeText = "";
            lyhMenuItem18.Enabled = true;
            lyhMenuItem18.Icon = null;
            lyhMenuItem18.IsExpanded = false;
            lyhMenuItem18.ItemBackColor = Color.Empty;
            lyhMenuItem18.ItemForeColor = Color.White;
            lyhMenuItem18.TargetPageName = "Cascader";
            lyhMenuItem18.Text = "级联选择器";
            lyhMenuItem19.BadgeText = "";
            lyhMenuItem19.Enabled = true;
            lyhMenuItem19.Icon = null;
            lyhMenuItem19.IsExpanded = false;
            lyhMenuItem19.ItemBackColor = Color.Empty;
            lyhMenuItem19.ItemForeColor = Color.White;
            lyhMenuItem19.TargetPageName = "Transfer";
            lyhMenuItem19.Text = "穿梭框";
            lyhMenuItem20.BadgeText = "";
            lyhMenuItem20.Enabled = true;
            lyhMenuItem20.Icon = null;
            lyhMenuItem20.IsExpanded = false;
            lyhMenuItem20.ItemBackColor = Color.Empty;
            lyhMenuItem20.ItemForeColor = Color.White;
            lyhMenuItem20.TargetPageName = "StarRate";
            lyhMenuItem20.Text = "星级评分";
            lyhMenuItem16.SubItems.Add(lyhMenuItem17);
            lyhMenuItem16.SubItems.Add(lyhMenuItem18);
            lyhMenuItem16.SubItems.Add(lyhMenuItem19);
            lyhMenuItem16.SubItems.Add(lyhMenuItem20);
            lyhMenuItem16.TargetPageName = "";
            lyhMenuItem16.Text = "选择器";
            lyhMenuItem11.SubItems.Add(lyhMenuItem12);
            lyhMenuItem11.SubItems.Add(lyhMenuItem16);
            lyhMenuItem11.TargetPageName = "";
            lyhMenuItem11.Text = "数据输入与采集";
            lyhMenuItem21.BadgeText = "";
            lyhMenuItem21.Enabled = true;
            lyhMenuItem21.Icon = Properties.Resources.Frame__2_1;
            lyhMenuItem21.IsExpanded = false;
            lyhMenuItem21.ItemBackColor = Color.Empty;
            lyhMenuItem21.ItemForeColor = Color.White;
            lyhMenuItem22.BadgeText = "";
            lyhMenuItem22.Enabled = true;
            lyhMenuItem22.Icon = null;
            lyhMenuItem22.IsExpanded = false;
            lyhMenuItem22.ItemBackColor = Color.Empty;
            lyhMenuItem22.ItemForeColor = Color.White;
            lyhMenuItem23.BadgeText = "";
            lyhMenuItem23.Enabled = true;
            lyhMenuItem23.Icon = null;
            lyhMenuItem23.IsExpanded = false;
            lyhMenuItem23.ItemBackColor = Color.Empty;
            lyhMenuItem23.ItemForeColor = Color.White;
            lyhMenuItem23.TargetPageName = "CircularGauge";
            lyhMenuItem23.Text = "环形仪表盘";
            lyhMenuItem24.BadgeText = "";
            lyhMenuItem24.Enabled = true;
            lyhMenuItem24.Icon = null;
            lyhMenuItem24.IsExpanded = false;
            lyhMenuItem24.ItemBackColor = Color.Empty;
            lyhMenuItem24.ItemForeColor = Color.White;
            lyhMenuItem24.TargetPageName = "LEDText";
            lyhMenuItem24.Text = "LED数码展示";
            lyhMenuItem25.BadgeText = "";
            lyhMenuItem25.Enabled = true;
            lyhMenuItem25.Icon = null;
            lyhMenuItem25.IsExpanded = false;
            lyhMenuItem25.ItemBackColor = Color.Empty;
            lyhMenuItem25.ItemForeColor = Color.White;
            lyhMenuItem25.TargetPageName = "Gauge_ProgressBar";
            lyhMenuItem25.Text = "仪表盘进度条";
            lyhMenuItem22.SubItems.Add(lyhMenuItem23);
            lyhMenuItem22.SubItems.Add(lyhMenuItem24);
            lyhMenuItem22.SubItems.Add(lyhMenuItem25);
            lyhMenuItem22.TargetPageName = "";
            lyhMenuItem22.Text = "监控仪表";
            lyhMenuItem26.BadgeText = "";
            lyhMenuItem26.Enabled = true;
            lyhMenuItem26.Icon = null;
            lyhMenuItem26.IsExpanded = false;
            lyhMenuItem26.ItemBackColor = Color.Empty;
            lyhMenuItem26.ItemForeColor = Color.White;
            lyhMenuItem27.BadgeText = "";
            lyhMenuItem27.Enabled = true;
            lyhMenuItem27.Icon = null;
            lyhMenuItem27.IsExpanded = false;
            lyhMenuItem27.ItemBackColor = Color.Empty;
            lyhMenuItem27.ItemForeColor = Color.White;
            lyhMenuItem27.TargetPageName = "SmoothProgressBar";
            lyhMenuItem27.Text = "平滑进度条";
            lyhMenuItem28.BadgeText = "";
            lyhMenuItem28.Enabled = true;
            lyhMenuItem28.Icon = null;
            lyhMenuItem28.IsExpanded = false;
            lyhMenuItem28.ItemBackColor = Color.Empty;
            lyhMenuItem28.ItemForeColor = Color.White;
            lyhMenuItem28.TargetPageName = "Normal_ProgressBar";
            lyhMenuItem28.Text = "普通进度条";
            lyhMenuItem29.BadgeText = "";
            lyhMenuItem29.Enabled = true;
            lyhMenuItem29.Icon = null;
            lyhMenuItem29.IsExpanded = false;
            lyhMenuItem29.ItemBackColor = Color.Empty;
            lyhMenuItem29.ItemForeColor = Color.White;
            lyhMenuItem29.TargetPageName = "SpinControl";
            lyhMenuItem29.Text = "加载等待动画";
            lyhMenuItem26.SubItems.Add(lyhMenuItem27);
            lyhMenuItem26.SubItems.Add(lyhMenuItem28);
            lyhMenuItem26.SubItems.Add(lyhMenuItem29);
            lyhMenuItem26.TargetPageName = "";
            lyhMenuItem26.Text = "进度展示";
            lyhMenuItem30.BadgeText = "";
            lyhMenuItem30.Enabled = true;
            lyhMenuItem30.Icon = null;
            lyhMenuItem30.IsExpanded = false;
            lyhMenuItem30.ItemBackColor = Color.Empty;
            lyhMenuItem30.ItemForeColor = Color.White;
            lyhMenuItem31.BadgeText = "";
            lyhMenuItem31.Enabled = true;
            lyhMenuItem31.Icon = null;
            lyhMenuItem31.IsExpanded = false;
            lyhMenuItem31.ItemBackColor = Color.Empty;
            lyhMenuItem31.ItemForeColor = Color.White;
            lyhMenuItem31.TargetPageName = "IndustrialTank";
            lyhMenuItem31.Text = "工业储罐";
            lyhMenuItem32.BadgeText = "";
            lyhMenuItem32.Enabled = true;
            lyhMenuItem32.Icon = null;
            lyhMenuItem32.IsExpanded = false;
            lyhMenuItem32.ItemBackColor = Color.Empty;
            lyhMenuItem32.ItemForeColor = Color.White;
            lyhMenuItem32.TargetPageName = "FlexiblePipe";
            lyhMenuItem32.Text = "柔性管道";
            lyhMenuItem33.BadgeText = "";
            lyhMenuItem33.Enabled = true;
            lyhMenuItem33.Icon = null;
            lyhMenuItem33.IsExpanded = false;
            lyhMenuItem33.ItemBackColor = Color.Empty;
            lyhMenuItem33.ItemForeColor = Color.White;
            lyhMenuItem33.TargetPageName = "IndustrialDevice";
            lyhMenuItem33.Text = "风扇及报警灯";
            lyhMenuItem30.SubItems.Add(lyhMenuItem31);
            lyhMenuItem30.SubItems.Add(lyhMenuItem32);
            lyhMenuItem30.SubItems.Add(lyhMenuItem33);
            lyhMenuItem30.TargetPageName = "";
            lyhMenuItem30.Text = "工业建模";
            lyhMenuItem21.SubItems.Add(lyhMenuItem22);
            lyhMenuItem21.SubItems.Add(lyhMenuItem26);
            lyhMenuItem21.SubItems.Add(lyhMenuItem30);
            lyhMenuItem21.TargetPageName = "";
            lyhMenuItem21.Text = "工业可视化与HMI";
            lyhMenuItem34.BadgeText = "";
            lyhMenuItem34.Enabled = true;
            lyhMenuItem34.Icon = Properties.Resources.Frame__3_1;
            lyhMenuItem34.IsExpanded = false;
            lyhMenuItem34.ItemBackColor = Color.Empty;
            lyhMenuItem34.ItemForeColor = Color.White;
            lyhMenuItem35.BadgeText = "";
            lyhMenuItem35.Enabled = true;
            lyhMenuItem35.Icon = null;
            lyhMenuItem35.IsExpanded = false;
            lyhMenuItem35.ItemBackColor = Color.Empty;
            lyhMenuItem35.ItemForeColor = Color.White;
            lyhMenuItem36.BadgeText = "";
            lyhMenuItem36.Enabled = true;
            lyhMenuItem36.Icon = null;
            lyhMenuItem36.IsExpanded = false;
            lyhMenuItem36.ItemBackColor = Color.Empty;
            lyhMenuItem36.ItemForeColor = Color.White;
            lyhMenuItem36.TargetPageName = "ModernDataGridView";
            lyhMenuItem36.Text = "高效数据表格";
            lyhMenuItem37.BadgeText = "";
            lyhMenuItem37.Enabled = true;
            lyhMenuItem37.Icon = null;
            lyhMenuItem37.IsExpanded = false;
            lyhMenuItem37.ItemBackColor = Color.Empty;
            lyhMenuItem37.ItemForeColor = Color.White;
            lyhMenuItem37.TargetPageName = "ModernRealtimeChart";
            lyhMenuItem37.Text = "高效动态曲线";
            lyhMenuItem38.BadgeText = "";
            lyhMenuItem38.Enabled = true;
            lyhMenuItem38.Icon = null;
            lyhMenuItem38.IsExpanded = false;
            lyhMenuItem38.ItemBackColor = Color.Empty;
            lyhMenuItem38.ItemForeColor = Color.White;
            lyhMenuItem38.TargetPageName = "RadarChart";
            lyhMenuItem38.Text = "雷达对比图";
            lyhMenuItem35.SubItems.Add(lyhMenuItem36);
            lyhMenuItem35.SubItems.Add(lyhMenuItem37);
            lyhMenuItem35.SubItems.Add(lyhMenuItem38);
            lyhMenuItem35.TargetPageName = "";
            lyhMenuItem35.Text = "图表分析";
            lyhMenuItem39.BadgeText = "";
            lyhMenuItem39.Enabled = true;
            lyhMenuItem39.Icon = null;
            lyhMenuItem39.IsExpanded = false;
            lyhMenuItem39.ItemBackColor = Color.Empty;
            lyhMenuItem39.ItemForeColor = Color.White;
            lyhMenuItem40.BadgeText = "";
            lyhMenuItem40.Enabled = true;
            lyhMenuItem40.Icon = null;
            lyhMenuItem40.IsExpanded = false;
            lyhMenuItem40.ItemBackColor = Color.Empty;
            lyhMenuItem40.ItemForeColor = Color.White;
            lyhMenuItem40.TargetPageName = "TreeMenu";
            lyhMenuItem40.Text = "侧边树状导航";
            lyhMenuItem41.BadgeText = "";
            lyhMenuItem41.Enabled = true;
            lyhMenuItem41.Icon = null;
            lyhMenuItem41.IsExpanded = false;
            lyhMenuItem41.ItemBackColor = Color.Empty;
            lyhMenuItem41.ItemForeColor = Color.White;
            lyhMenuItem41.TargetPageName = "OrgChart";
            lyhMenuItem41.Text = "组织架构图";
            lyhMenuItem42.BadgeText = "";
            lyhMenuItem42.Enabled = true;
            lyhMenuItem42.Icon = null;
            lyhMenuItem42.IsExpanded = false;
            lyhMenuItem42.ItemBackColor = Color.Empty;
            lyhMenuItem42.ItemForeColor = Color.White;
            lyhMenuItem42.TargetPageName = "TimeLine";
            lyhMenuItem42.Text = "时间轴";
            lyhMenuItem43.BadgeText = "";
            lyhMenuItem43.Enabled = true;
            lyhMenuItem43.Icon = null;
            lyhMenuItem43.IsExpanded = false;
            lyhMenuItem43.ItemBackColor = Color.Empty;
            lyhMenuItem43.ItemForeColor = Color.White;
            lyhMenuItem43.TargetPageName = "StepItem";
            lyhMenuItem43.Text = "步骤条";
            lyhMenuItem39.SubItems.Add(lyhMenuItem40);
            lyhMenuItem39.SubItems.Add(lyhMenuItem41);
            lyhMenuItem39.SubItems.Add(lyhMenuItem42);
            lyhMenuItem39.SubItems.Add(lyhMenuItem43);
            lyhMenuItem39.TargetPageName = "";
            lyhMenuItem39.Text = "结构展示";
            lyhMenuItem44.BadgeText = "";
            lyhMenuItem44.Enabled = true;
            lyhMenuItem44.Icon = null;
            lyhMenuItem44.IsExpanded = false;
            lyhMenuItem44.ItemBackColor = Color.Empty;
            lyhMenuItem44.ItemForeColor = Color.White;
            lyhMenuItem45.BadgeText = "";
            lyhMenuItem45.Enabled = true;
            lyhMenuItem45.Icon = null;
            lyhMenuItem45.IsExpanded = false;
            lyhMenuItem45.ItemBackColor = Color.Empty;
            lyhMenuItem45.ItemForeColor = Color.White;
            lyhMenuItem45.TargetPageName = "Pagination";
            lyhMenuItem45.Text = "标准数据分页";
            lyhMenuItem46.BadgeText = "";
            lyhMenuItem46.Enabled = true;
            lyhMenuItem46.Icon = null;
            lyhMenuItem46.IsExpanded = false;
            lyhMenuItem46.ItemBackColor = Color.Empty;
            lyhMenuItem46.ItemForeColor = Color.White;
            lyhMenuItem46.TargetPageName = "MiniPagination";
            lyhMenuItem46.Text = "迷你分页";
            lyhMenuItem47.BadgeText = "";
            lyhMenuItem47.Enabled = true;
            lyhMenuItem47.Icon = null;
            lyhMenuItem47.IsExpanded = false;
            lyhMenuItem47.ItemBackColor = Color.Empty;
            lyhMenuItem47.ItemForeColor = Color.White;
            lyhMenuItem47.TargetPageName = "Breadcrumb";
            lyhMenuItem47.Text = "面包屑导航";
            lyhMenuItem44.SubItems.Add(lyhMenuItem45);
            lyhMenuItem44.SubItems.Add(lyhMenuItem46);
            lyhMenuItem44.SubItems.Add(lyhMenuItem47);
            lyhMenuItem44.TargetPageName = "";
            lyhMenuItem44.Text = "分页导航";
            lyhMenuItem34.SubItems.Add(lyhMenuItem35);
            lyhMenuItem34.SubItems.Add(lyhMenuItem39);
            lyhMenuItem34.SubItems.Add(lyhMenuItem44);
            lyhMenuItem34.TargetPageName = "";
            lyhMenuItem34.Text = "数据图表与导航";
            lyhMenuItem48.BadgeText = "";
            lyhMenuItem48.Enabled = true;
            lyhMenuItem48.Icon = Properties.Resources.Icon__75_1;
            lyhMenuItem48.IsExpanded = false;
            lyhMenuItem48.ItemBackColor = Color.Empty;
            lyhMenuItem48.ItemForeColor = Color.White;
            lyhMenuItem49.BadgeText = "";
            lyhMenuItem49.Enabled = true;
            lyhMenuItem49.Icon = null;
            lyhMenuItem49.IsExpanded = false;
            lyhMenuItem49.ItemBackColor = Color.Empty;
            lyhMenuItem49.ItemForeColor = Color.White;
            lyhMenuItem50.BadgeText = "";
            lyhMenuItem50.Enabled = true;
            lyhMenuItem50.Icon = null;
            lyhMenuItem50.IsExpanded = false;
            lyhMenuItem50.ItemBackColor = Color.Empty;
            lyhMenuItem50.ItemForeColor = Color.White;
            lyhMenuItem50.TargetPageName = "Alert";
            lyhMenuItem50.Text = "信息提示框";
            lyhMenuItem49.SubItems.Add(lyhMenuItem50);
            lyhMenuItem49.TargetPageName = "";
            lyhMenuItem49.Text = "全局通知";
            lyhMenuItem51.BadgeText = "";
            lyhMenuItem51.Enabled = true;
            lyhMenuItem51.Icon = null;
            lyhMenuItem51.IsExpanded = false;
            lyhMenuItem51.ItemBackColor = Color.Empty;
            lyhMenuItem51.ItemForeColor = Color.White;
            lyhMenuItem52.BadgeText = "";
            lyhMenuItem52.Enabled = true;
            lyhMenuItem52.Icon = null;
            lyhMenuItem52.IsExpanded = false;
            lyhMenuItem52.ItemBackColor = Color.Empty;
            lyhMenuItem52.ItemForeColor = Color.White;
            lyhMenuItem52.TargetPageName = "Carousel";
            lyhMenuItem52.Text = "跑马灯预览";
            lyhMenuItem53.BadgeText = "";
            lyhMenuItem53.Enabled = true;
            lyhMenuItem53.Icon = null;
            lyhMenuItem53.IsExpanded = false;
            lyhMenuItem53.ItemBackColor = Color.Empty;
            lyhMenuItem53.ItemForeColor = Color.White;
            lyhMenuItem53.TargetPageName = "WatermarkProvider";
            lyhMenuItem53.Text = "水印提供器";
            lyhMenuItem54.BadgeText = "";
            lyhMenuItem54.Enabled = true;
            lyhMenuItem54.Icon = null;
            lyhMenuItem54.IsExpanded = false;
            lyhMenuItem54.ItemBackColor = Color.Empty;
            lyhMenuItem54.ItemForeColor = Color.White;
            lyhMenuItem54.TargetPageName = "RoundControl";
            lyhMenuItem54.Text = "柔边圆形控件";
            lyhMenuItem51.SubItems.Add(lyhMenuItem52);
            lyhMenuItem51.SubItems.Add(lyhMenuItem53);
            lyhMenuItem51.SubItems.Add(lyhMenuItem54);
            lyhMenuItem51.TargetPageName = "";
            lyhMenuItem51.Text = "内容布局";
            lyhMenuItem55.BadgeText = "";
            lyhMenuItem55.Enabled = true;
            lyhMenuItem55.Icon = null;
            lyhMenuItem55.IsExpanded = false;
            lyhMenuItem55.ItemBackColor = Color.Empty;
            lyhMenuItem55.ItemForeColor = Color.White;
            lyhMenuItem56.BadgeText = "";
            lyhMenuItem56.Enabled = true;
            lyhMenuItem56.Icon = null;
            lyhMenuItem56.IsExpanded = false;
            lyhMenuItem56.ItemBackColor = Color.Empty;
            lyhMenuItem56.ItemForeColor = Color.White;
            lyhMenuItem56.TargetPageName = "QRCode";
            lyhMenuItem56.Text = "二维码生成";
            lyhMenuItem57.BadgeText = "";
            lyhMenuItem57.Enabled = true;
            lyhMenuItem57.Icon = null;
            lyhMenuItem57.IsExpanded = false;
            lyhMenuItem57.ItemBackColor = Color.Empty;
            lyhMenuItem57.ItemForeColor = Color.White;
            lyhMenuItem57.TargetPageName = "Stable3DViewer";
            lyhMenuItem57.Text = "3D模型渲染";
            lyhMenuItem55.SubItems.Add(lyhMenuItem56);
            lyhMenuItem55.SubItems.Add(lyhMenuItem57);
            lyhMenuItem55.TargetPageName = "";
            lyhMenuItem55.Text = "特殊展示";
            lyhMenuItem48.SubItems.Add(lyhMenuItem49);
            lyhMenuItem48.SubItems.Add(lyhMenuItem51);
            lyhMenuItem48.SubItems.Add(lyhMenuItem55);
            lyhMenuItem48.TargetPageName = "";
            lyhMenuItem48.Text = "提示、反馈与布局 ";
            lyhMenuItem58.BadgeText = "";
            lyhMenuItem58.Enabled = true;
            lyhMenuItem58.Icon = null;
            lyhMenuItem58.IsExpanded = false;
            lyhMenuItem58.ItemBackColor = Color.Empty;
            lyhMenuItem58.ItemForeColor = Color.White;
            lyhMenuItem58.TargetPageName = "About";
            lyhMenuItem58.Text = "关于授权";
            treeMenu1.Items.Add(lyhMenuItem1);
            treeMenu1.Items.Add(lyhMenuItem2);
            treeMenu1.Items.Add(lyhMenuItem11);
            treeMenu1.Items.Add(lyhMenuItem21);
            treeMenu1.Items.Add(lyhMenuItem34);
            treeMenu1.Items.Add(lyhMenuItem48);
            treeMenu1.Items.Add(lyhMenuItem58);
            treeMenu1.Location = new Point(0, 90);
            treeMenu1.Margin = new Padding(2);
            treeMenu1.Name = "treeMenu1";
            treeMenu1.RootItemBackColor = SystemColors.HotTrack;
            treeMenu1.SeparatorColor = Color.WhiteSmoke;
            treeMenu1.Size = new Size(220, 990);
            treeMenu1.SubItemBackColor = SystemColors.HotTrack;
            treeMenu1.TabIndex = 0;
            treeMenu1.TargetStackedWidget = mainwindow;
            treeMenu1.Text = "treeMenu1";
            treeMenu1.ThemeColor = Color.FromArgb(22, 119, 255);
            // 
            // mainwindow
            // 
            mainwindow.Location = new Point(220, 90);
            mainwindow.Name = "mainwindow";
            mainwindow.Size = new Size(1700, 990);
            mainwindow.TabIndex = 2;
            // 
            // panel1
            // 
            panel1.BackColor = Color.FromArgb(251, 252, 253);
            panel1.Controls.Add(label2);
            panel1.Controls.Add(label1);
            panel1.Controls.Add(pictureBox1);
            panel1.Location = new Point(0, 0);
            panel1.Margin = new Padding(2);
            panel1.Name = "panel1";
            panel1.Size = new Size(1920, 90);
            panel1.TabIndex = 1;
            // 
            // label2
            // 
            label2.BackColor = Color.FromArgb(209, 213, 220);
            label2.Location = new Point(0, 88);
            label2.Name = "label2";
            label2.Size = new Size(1920, 2);
            label2.TabIndex = 2;
            label2.Text = "label2";
            // 
            // label1
            // 
            label1.Font = new Font("HarmonyOS Sans SC", 30F, FontStyle.Bold, GraphicsUnit.Pixel, 134);
            label1.Location = new Point(765, 23);
            label1.Margin = new Padding(2, 0, 2, 0);
            label1.Name = "label1";
            label1.Size = new Size(611, 45);
            label1.TabIndex = 1;
            label1.Text = "基于.NET 8打造的 C#(Winform) 控件库";
            label1.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // pictureBox1
            // 
            pictureBox1.BackgroundImage = Properties.Resources.savehmi;
            pictureBox1.BackgroundImageLayout = ImageLayout.Stretch;
            pictureBox1.Location = new Point(0, 0);
            pictureBox1.Margin = new Padding(2);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(220, 88);
            pictureBox1.TabIndex = 0;
            pictureBox1.TabStop = false;
            pictureBox1.Click += pictureBox1_Click;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(7F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(240, 244, 250);
            ClientSize = new Size(1920, 1080);
            Controls.Add(mainwindow);
            Controls.Add(panel1);
            Controls.Add(treeMenu1);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Margin = new Padding(2);
            Name = "Form1";
            Text = "Form1";
            panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private LYHControls.TreeMenu treeMenu1;
        private Panel panel1;
        private PictureBox pictureBox1;
        private Label label1;
        private Panel mainwindow;
        private Label label2;
    }
}
